apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argo-tunnel.fullname" . }}
  labels:
    {{- include "argo-tunnel.labels" . | nindent 4 }}
type: Opaque
data:
  tunnel: {{ .Values.tunnel.credentials | b64enc }}